print (float(3.14))
print(float(True))
print(float(False))
print(float("4"))
print(float(3))

print(complex(3))
print(complex(12.5))
print(complex(True))
print(complex(False))
print(complex("5"))
print(complex("5.6"))
# print(complex("Piyush"))
print(complex(5,-3))
print(complex(True,False))

print(bool(0))
print(bool(False))
print(bool(3.14))
print(bool(0.0))
print(bool(1+2))
print(bool(0+0))
print(bool(-1))
print(bool(True))
